### ISSUE TITLE
Nested include directories are not resolved

### ISSUE THREAD

**Issue by iXP0Mt** [NiceFeatures/amxxpawn-language#12]
### Bug

In v1.5.6, compilation fails when an .inc file is located inside a subdirectory of a configured include path

### Reproduction

Project structure:

```
~/plugin.sma
~/src/
    └── Helper/
        └── DataLoader.inc
```

File `~/plugin.sma`

```pawn
#include <amxmodx>

#include <Helper/DataLoader>

public plugin_init() 
{
    load()
}
```

File `~/src/Helper/DataLoader.inc`

```pawn
load()
{
    
}
```

settings.json

```json
"amxxpawn.compiler.includePaths":  [
    "${workspaceRoot}/src",
 ]
```

In this case get error compiler:

```
Starting amxxpc: "{CompilerDir}/Compiler1.10.0/amxxpc.exe" "{PluginDir}\plugin.sma" "-i{CompilerDir}/include" "-o{PluginDir}\plugin.amxx"

❌ Compilation failed after 0.053 seconds. See errors above.

amxxpc process finished with exit code 1.
```

However if I add empty `.inc` file in `src` directory like `~/src/dummy.inc` then compilation succeeds:

```
Starting amxxpc: "{CompilerDir}/Compiler1.10.0/amxxpc.exe" "{PluginDir}\plugin.sma" "-i{pluginDir}/src" "-i{CompilerDir}/include" "-o{PluginDir}\plugin.amxx"

╔════════════════════════════════════════════════
║ ✅  Compilation Succeeded!
╠════════════════════════════════════════════════
║ Plugin:     plugin.amxx
║ Output:     {PluginDir}\plugin.amxx
║ Size:       0.69 KB
║ Time:       0.078 seconds
╟────────────────────────────────────────────────
║ Compiler Statistics:
║   Header:     152 bytes
║   Code:       60 bytes
║   Data:       20 bytes
║   Total Req.: 16616 bytes
╚════════════════════════════════════════════════

```

---

Adding `/**` like `${workspaceRoot}/src/**` not resolve it. Also `/`, `/*`

The same code works correctly with v1.5.5

**Comment by NiceFeatures** [comment]
Thanks for reporting, see new v1.5.7 non released.

**Comment by iXP0Mt** [comment]
Tested on v1.5.7. Compilation works correctly now. Thanks! 
I also noticed the #include hint appeared. Special thanks for that!
